### ISSUE TITLE
TypeError: this[method] is not a function

### ISSUE THREAD

**Issue by srinisubra** [deepu105/generator-jhipster-bootswatch#1]
Hi deepu105, I followed the same route as i did for generator-jhipster-entity-audit/ https://github.com/deepu105/generator-jhipster-entity-audit/issues/2. 

But i am facing the below issue

vagrant@vagrant-ubuntu-trusty-64:~/git/rsidapp$ yo jhipster-bootswatch
(!) require('yeoman-generator').generators.Base is deprecated. Use require('yeoman-generator').Base directly
Composing JHipster configuration with module entity-audit
Welcome to the JHipster Bootswatch Module! v0.2.1

? Would you like to enable Bootswatch themes? Yes
Reading the JHipster project configuration for your module
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: this[method] is not a function
    at Object.<anonymous> (/home/vagrant/git/genJHipster/generator-jhipster/script-base.js:227:25)
    at Array.forEach (native)
    at Object.Generator.addTranslationKeyToAllLanguages (/home/vagrant/git/genJHipster/generator-jhipster/script-base.js:226:41)
    at module.exports.yeoman.generators.Base.extend.writing.updateClientSideFiles (/home/vagrant/git/genJHipster/generator-jhipster-bootswatch/generators/app/index.js:86:20)
    at Object.<anonymous> (/home/vagrant/git/genJHipster/generator-jhipster-bootswatch/node_modules/yeoman-generator/lib/base.js:436:25)
    at /home/vagrant/git/genJHipster/generator-jhipster-bootswatch/node_modules/yeoman-generator/node_modules/run-async/index.js:33:25
    at /home/vagrant/git/genJHipster/generator-jhipster-bootswatch/node_modules/yeoman-generator/lib/base.js:446:8
    at processImmediate [as _immediateCallback](timers.js:383:17)

**Comment by deepu105** [comment]
Can you clone the jhipster master branch from jhipster repo, not my fork,
as these methods are merged and is available in the jhipster master branch.

Let me know if you face any issue even after that.

Once the next jhipster version is released this should be smooth

**Comment by srinisubra** [comment]
Thanks this got resolved. Cool themes. Steps followed
1) git clone https://github.com/jhipster/generator-jhipster.git -b master
2) cd generator-jhipster
3) npm link
4)cd to_your_project
5)npm install -g generator-jhipster-bootswatch
6)yo jhipster-bootswatch

**Comment by deepu105** [comment]
Great glad you liked it
