### ISSUE TITLE
Error while using module

### ISSUE THREAD

**Issue by manishgoyaler** [deepu105/generator-jhipster-bootswatch#2]
Hi Deepu, 
I am getting error while using module. 

Repo is here.
https://github.com/manishgoyaler/jhipster_sample.git

(!) require('yeoman-generator').generators.Base is deprecated. Use require('yeoman-generator').Base directly
Composing JHipster configuration with module entity-audit
Welcome to the JHipster Bootswatch Module! v0.2.1

? Would you like to enable Bootswatch themes? Yes
Reading the JHipster project configuration for your module
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: jhipsterFunc.copyTemplate is not a function
    at null.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-bootswatch/generators/app/index.js:60:24)
    at Array.forEach (native)
    at copyFiles (/usr/local/lib/node_modules/generator-jhipster-bootswatch/generators/app/index.js:59:15)
    at module.exports.yeoman.generators.Base.extend.writing.writeClientSideFiles (/usr/local/lib/node_modules/generator-jhipster-bootswatch/generators/app/index.js:75:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-bootswatch/node_modules/yeoman-generator/lib/base.js:436:25)
    at /usr/local/lib/node_modules/generator-jhipster-bootswatch/node_modules/yeoman-generator/node_modules/run-async/index.js:33:25
    at /usr/local/lib/node_modules/generator-jhipster-bootswatch/node_modules/yeoman-generator/lib/base.js:446:8
    at processImmediate [as _immediateCallback](timers.js:368:17)

**Comment by deepu105** [comment]
As stated in the read me this module will work with the next Jhipster
version release which should be soon.

In the meanwhile if you want to use this, plz clone the master branch of
jhipster  and do npm link inside the folder to use it instead of global npm
module
